// Code generated by hertz generator.

package main

import (
	"Douyin/router"
	"Douyin/router/comment_router"
	"Douyin/router/favorate_router"
	"Douyin/router/user_router"
	"Douyin/router/video_router"
	"github.com/gin-gonic/gin"
)

func main() {
	r := gin.Default()
	r.Static("/static", "./public")
	root := r.Group("/douyin", router.RootMw())
	user_router.Register(root)
	video_router.Register(root)
	favorate_router.Register(root)
	comment_router.Register(root)
	r.Run()

}
