// Code generated by hertz generator.

package main

import (
	"DouYin-Proj/biz/router"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default(server.WithHostPorts("0.0.0.0:8080"))
	router.GeneratedRegister(h)
	h.Spin()
}
